
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Frame3 extends javax.swing.JFrame {

    /**
     * Creates new form Frame3
     */
    public Frame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        Panjang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Balok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Kubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Jari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Bola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 290, 40);

        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Masukkan Tinggi      :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 110, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Masukkan Lebar       :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 70, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Masukkan Panjang   :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 30, 150, 30);
        jPanel1.add(Tinggi);
        Tinggi.setBounds(190, 110, 110, 30);
        jPanel1.add(Lebar);
        Lebar.setBounds(190, 70, 110, 30);

        Panjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanjangActionPerformed(evt);
            }
        });
        jPanel1.add(Panjang);
        Panjang.setBounds(190, 30, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("cm");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 110, 40, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("cm");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 70, 40, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("cm");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 30, 40, 30);

        Balok.setText("Hitung");
        Balok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalokActionPerformed(evt);
            }
        });
        jPanel1.add(Balok);
        Balok.setBounds(190, 160, 110, 23);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 20, 150, 30);
        jPanel2.add(Sisi);
        Sisi.setBounds(20, 50, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(170, 50, 40, 20);

        Kubus.setText("Volume");
        Kubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KubusActionPerformed(evt);
            }
        });
        jPanel2.add(Kubus);
        Kubus.setBounds(20, 90, 70, 23);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Masukkan Panjang Jari-jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 20, 180, 30);
        jPanel3.add(Jari);
        Jari.setBounds(20, 50, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(190, 50, 17, 30);

        Bola.setText("Volume");
        Bola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolaActionPerformed(evt);
            }
        });
        jPanel3.add(Bola);
        Bola.setBounds(20, 90, 70, 23);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 60, 400, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanjangActionPerformed

    private void BalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalokActionPerformed
        int panjang, lebar, tinggi;
        panjang=Integer.parseInt(Panjang.getText());
        lebar=Integer.parseInt(Lebar.getText());
        tinggi=Integer.parseInt(Tinggi.getText());
        int hasil=panjang*lebar*tinggi;
        try {
            JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BalokActionPerformed

    private void KubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KubusActionPerformed
        int sisi;
        sisi=Integer.parseInt(Sisi.getText());
        int hasil=sisi*sisi*sisi;
        
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus Adalah : "
                +hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_KubusActionPerformed

    private void BolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolaActionPerformed
        float jari;
        jari=Integer.parseInt(Jari.getText());
        float hasil=(float) (4/3*3.14*jari*jari*jari);
        try {
            JOptionPane.showMessageDialog(null,"Luas Permukaan Bola Adalah : "
                +hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error:"+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Balok;
    private javax.swing.JButton Bola;
    private javax.swing.JTextField Jari;
    private javax.swing.JButton Kubus;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
